# Week 1 : Pandas

Pandas is a powerful column oriented data analysis API. It is mainly used for data handling and analyzing input data and is widely supported by Machine Learning libraries. It is built on top of NumPy and provides a lot of functionality to work with data in a more efficient way.

Uisng pandas we can import, display, manipulate and analyze data. It is like Excel but for python.

## Benifits Of Using Pandas : 

1. Easy to use and make code clean
2. Comes out of the box with a lot of handy tools for data manipulation and analysis
3. Very similar to excel and SQL which makes it easy to learn and use
4. Handles very large datasets efficiently
5. Provides powerful data visualization capabilities

## Load Pandas Library

Install pandas using pip or uv if using virtual environment.

```bash
pip install pandas
```

```bash
uv add pandas
```

In [2]:
# Importing Pandas

import pandas as pd  # Common convention to use pandas as pd
import numpy as np  # Common convention to use numpy as np

pd.__version__
np.__version__

'2.4.2'

## Dataframes

One of the most important data structures in pandas is the DataFrame. A DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. It is similar to a spreadsheet or SQL table, and it is one of the most commonly used data structures in pandas.

Dataframe is like a relational data table where there is a relationship between rows and columns. It is a 2-dimensional data structure that can hold data of different types (integer, float, string, etc.) in columns. Each column can be thought of as a Series, which is a one-dimensional array-like object.

Dataframe can be thought as a matrix with rows and columns, where each column can have a different data type.

In [ ]:
# Creating a DataFrame with columns 'name' and 'age'

df = pd.DataFrame({"name": ["Soham", "Samar", "Yash"], "age": [19, 20, 24]})

# Visualizing the dataframe would look like :
#     name   age
# 0  Soham   19
# 1  Samar   20
# 2   Yash   24

# Each column is a Series (1D array with index).
# Rows are indexed starting from 0 by default.

type(df)

# To access a column, we can use the column name as an attribute or as a key

df.name  # Accessing 'name' column as an attribute
df["name"]  # Accessing 'name' column as a key

# To access a particular row, we can use the .loc or .iloc indexers. .loc is label-based, while .iloc is integer position-based.

print(df.loc[0])  # Accessing the first row using .loc
print(df.iloc[0])  # Accessing the first row using .iloc

# accessing row with a element
print(df.loc[df["name"] == "Samar"])  # Accessing row where name is 'Samar'

# updating a value in the dataframe, for example changing the age of Samar to 21
df.loc[df["name"] == "Samar", "age"] = 21

# we can add new columns, wehen doing so each and every row must have the data

df["job"] = ["Nalla", "Intern", "Job"]

# we can also add a new row and for that we need to give a dictionary with the given key value pairs

new_row = pd.DataFrame({"name": ["No Idea"], "age": ["No Idea"], "job": ["No Idea"]})

# now we will con-catinate the old df and new df using concat function and passing old and new df in a list as a param, we can essentailly add n number of rows

df = pd.concat([df, new_row])
print(df)

# if while concatinating, a coloumn has a data which the other df dosen't it will default as NaN -
# for example if df_1 has column phone, and df_2 while concatinating dosen't have phone it would be NaN by deafult

name    Soham
age        19
Name: 0, dtype: object
name    Soham
age        19
Name: 0, dtype: object
      name      age      job
0    Soham       19    Nalla
1    Samar       20   Intern
2     Yash       24      Job
0  No Idea  No Idea  No Idea

## Series

A Series is a one-dimensional labeled array that can hold data of any type (integer, float, string, etc.). It is similar to a column in a DataFrame. Each element in a Series has an associated label, which is called the index. The index can be thought of as the row labels in a DataFrame.

A Series can be created from a list, a NumPy array, or a dictionary. It can also be created from a DataFrame by selecting a single column.

A Series can be thought of as a single column of a DataFrame, and it can be used to perform various operations such as indexing, slicing, and mathematical operations. Or it can be thought of a vector of data with an associated index.

In [31]:
# Creating a series with columns 'name'

sr = pd.Series(["Soham", "Samar", "Yash"])

# Visualizing the series would look like :
# 0 Soham
# 1 Samar
# 2 Yash

# Each element is a element of the 1D array.
# Each element is indexed starting from 0 by deafult.

type(sr)
print(sr)

# we can have a custom index as well, by passing the keyword index

sr = pd.Series(
    ["Soham", "Samar", "Yash"], index=["a", "b", "c"]
)  # It is considered as a lable, and can contain anything

print(sr)

# To access an element directly by the lable, we use the loc operator
# Accessing Samar using the lable we will do -

print(sr.loc["b"])  # Return the value where lable is b

# Using loc we can update the elements easily

sr.loc["c"] = "Yashuuu"
print(sr)

# if I have to return using the integer index value then we will use the iloc operator

print(sr.iloc[1])  # will return samar cause according to numerical index Samar is at 1

# NOTE : index must always match the number of elements, if that's not the case then it will turn a ValueError

# We can easily perform filter by providing the condition in []
# for example i am trying to get the name of the user who has letter u in his name

print(sr[sr.str.contains("u")])

# here i am using .str.contains() which checks each element of series for a substring presence and returns a boolean

# We can use dic as a series as well -
calories = {"Day 1": 1750, "Day 2": 100, "Day 3": 700}

sr_2 = pd.Series(calories)
sr_2.loc["Day 2"] += 500 # adding 500 more to day 2

print(sr_2)

0    Soham
1    Samar
2     Yash
dtype: str
a    Soham
b    Samar
c     Yash
dtype: str
Samar
a      Soham
b      Samar
c    Yashuuu
dtype: str
Samar
c    Yashuuu
dtype: str
Day 1    1750
Day 2     600
Day 3     700
dtype: int64

In [32]:
data = ["Bulbasaur", "Ivysaur", "Venusaur", "Charmander", "Charmeleon", "Charizard"]

pokemon_series = pd.Series(data)

print(pokemon_series)

0     Bulbasaur
1       Ivysaur
2      Venusaur
3    Charmander
4    Charmeleon
5     Charizard
dtype: str

### Essentially a Series is a one-dimensional labled array, while a DataFrame is a two-dimensional table with rows and columns, where each column can be thought of as a Series. Dataframe is formed by combining multiple Series together.

## Loading Data

We can load any data into a DataFrame or Series essentially using the `read_csv` function. This function can read data from a CSV file and create a DataFrame from it.

In [84]:
df = pd.read_csv("../Resources/Data/Pokemon.csv")

print(df.to_string()) # properly displays entire dataset in tabular form

      Pokedex Number                            Name    Type 1    Type 2  Base Stat Total     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation Legendary Sub Legendary Mythical Mega
0                  1                       Bulbasaur     Grass    Poison            318.0   45.0    49.0     49.0     65.0     65.0   45.0         1.0        No            No       No   No
1                  2                         Ivysaur     Grass    Poison            405.0   60.0    62.0     63.0     80.0     80.0   60.0         1.0       NaN           NaN      NaN  NaN
2                  3                        Venusaur     Grass    Poison            525.0   80.0    82.0     83.0    100.0    100.0   80.0         1.0       NaN           NaN      NaN  NaN
3                  3                   Mega Venusaur     Grass    Poison            625.0   80.0   100.0    123.0    122.0    120.0   80.0         1.0       NaN           NaN      NaN  NaN
4                  4                      Charmander      Fire       NaN            309.0   39.0    52.0     43.0     60.0     50.0   65.0         1.0       NaN           NaN      NaN  NaN
5                  5                      Charmeleon      Fire       NaN            405.0   58.0    64.0     58.0     80.0     65.0   80.0         1.0       NaN           NaN      NaN  NaN
6                  6                       Charizard      Fire    Flying            534.0   78.0    84.0     78.0    109.0     85.0  100.0         1.0       NaN           NaN      NaN  NaN
7                  6                Mega Charizard X      Fire    Dragon            634.0   78.0   130.0    111.0    130.0     85.0  100.0         1.0       NaN           NaN      NaN  NaN
8                  6                Mega Charizard Y      Fire    Flying            634.0   78.0   104.0     78.0    159.0    115.0  100.0         1.0       NaN           NaN      NaN  NaN
9                  7                        Squirtle     Water       NaN            314.0   44.0    48.0     65.0     50.0     64.0   43.0         1.0       NaN           NaN      NaN  NaN
10                 8                       Wartortle     Water       NaN            405.0   59.0    63.0     80.0     65.0     80.0   58.0         1.0       NaN           NaN      NaN  NaN
11                 9                       Blastoise     Water       NaN            530.0   79.0    83.0    100.0     85.0    105.0   78.0         1.0       NaN           NaN      NaN  NaN
12                 9                  Mega Blastoise     Water       NaN            630.0   79.0   103.0    120.0    135.0    115.0   78.0         1.0       NaN           NaN      NaN  NaN
13                10                        Caterpie       Bug       NaN            195.0   45.0    30.0     35.0     20.0     20.0   45.0         1.0       NaN           NaN      NaN  NaN
14                11                         Metapod       Bug       NaN            205.0   50.0    20.0     55.0     25.0     25.0   30.0         1.0       NaN           NaN      NaN  NaN
15                12                      Butterfree       Bug    Flying            395.0   60.0    45.0     50.0     90.0     80.0   70.0         1.0       NaN           NaN      NaN  NaN
16                13                          Weedle       Bug    Poison            195.0   40.0    35.0     30.0     20.0     20.0   50.0         1.0       NaN           NaN      NaN  NaN
17                14                          Kakuna       Bug    Poison            205.0   45.0    25.0     50.0     25.0     25.0   35.0         1.0       NaN           NaN      NaN  NaN
18                15                        Beedrill       Bug    Poison            395.0   65.0    90.0     40.0     45.0     80.0   75.0         1.0       NaN           NaN      NaN  NaN
19                15                   Mega Beedrill       Bug    Poison            495.0   65.0   150.0     40.0     15.0     80.0  145.0         1.0       NaN           NaN      NaN  NaN
20                16                          Pidgey    Normal    Flying            251.0   40.0    45.0     40.0     35.0     35.0   56.0         1.0       NaN           NaN      NaN  NaN
21                17                       Pidgeotto    Normal    Flying            349.0   63.0    60.0     55.0     50.0     50.0   71.0         1.0       NaN           NaN      NaN  NaN
22                18                         Pidgeot    Normal    Flying            479.0   83.0    80.0     75.0     70.0     70.0  101.0         1.0       NaN           NaN      NaN  NaN
23                18                    Mega Pidgeot    Normal    Flying            579.0   83.0    80.0     80.0    135.0     80.0  121.0         1.0       NaN           NaN      NaN  NaN
24                19                         Rattata    Normal       NaN            253.0   30.0    56.0     35.0     25.0     35.0   72.0         1.0       NaN           NaN      NaN  NaN
25                20                        Raticate    Normal       NaN            413.0   55.0    81.0     60.0     50.0     70.0   97.0         1.0       NaN           NaN      NaN  NaN
26                21                         Spearow    Normal    Flying            262.0   40.0    60.0     30.0     31.0     31.0   70.0         1.0       NaN           NaN      NaN  NaN
27                22                          Fearow    Normal    Flying            442.0   65.0    90.0     65.0     61.0     61.0  100.0         1.0       NaN           NaN      NaN  NaN
28                23                           Ekans    Poison       NaN            288.0   35.0    60.0     44.0     40.0     54.0   55.0         1.0       NaN           NaN      NaN  NaN
29                24                           Arbok    Poison       NaN            438.0   60.0    85.0     69.0     65.0     79.0   80.0         1.0       NaN           NaN      NaN  NaN
30                25                         Pikachu  Electric       NaN            320.0   35.0    55.0     40.0     50.0     50.0   90.0         1.0       NaN           NaN      NaN  NaN
31                26                          Raichu  Electric       NaN            485.0   60.0    90.0     55.0     90.0     80.0  110.0         1.0       NaN           NaN      NaN  NaN
32                26                   Mega Raichu X       NaN       NaN              NaN    NaN     NaN      NaN      NaN      NaN    NaN         NaN       NaN           NaN      NaN  NaN
33                26                   Mega Raichu Y       NaN       NaN              NaN    NaN     NaN      NaN      NaN      NaN    NaN         NaN       NaN           NaN      NaN  NaN
34                27                       Sandshrew    Ground       NaN            300.0   50.0    75.0     85.0     20.0     30.0   40.0         1.0       NaN           NaN      NaN  NaN
35                28                       Sandslash    Ground       NaN            450.0   75.0   100.0    110.0     45.0     55.0   65.0         1.0       NaN           NaN      NaN  NaN
36                29                Nidoran (Female)    Poison       NaN            275.0   55.0    47.0     52.0     40.0     40.0   41.0         1.0       NaN           NaN      NaN  NaN
37                30                        Nidorina    Poison       NaN            365.0   70.0    62.0     67.0     55.0     55.0   56.0         1.0       NaN           NaN      NaN  NaN
38                31                       Nidoqueen    Poison    Ground            505.0   90.0    92.0     87.0     75.0     85.0   76.0         1.0       NaN           NaN      NaN  NaN
39                32                  Nidoran (Male)    Poison       NaN            273.0   46.0    57.0     40.0     40.0     40.0   50.0         1.0       NaN           NaN      NaN  NaN
40                33                        Nidorino    Poison       NaN            365.0   61.0    72.0     57.0     55.0     55.0   65.0         1.0       NaN           NaN      NaN  NaN
41                34                        Nidoking    Poison    Ground            505.0   81.0   102.0     77.0     85.0     75.0   85.0         1.0       NaN           NaN      NaN  NaN
42                35                        Clefairy     Fairy       NaN            323.0   70.0    45.0     48.0     60.0     65.0   35.0         1.0       NaN           NaN      NaN  NaN
43                36                        Clefable     Fairy       NaN            483.0   95.0    70.0     73.0     95.0     90.0   60.0         1.0       NaN           NaN      NaN  NaN
44                36                   Mega Clefable       NaN       NaN              NaN    NaN     NaN      NaN      NaN      NaN    NaN         NaN       NaN           NaN      NaN  NaN
45                37                          Vulpix      Fire       NaN            299.0   38.0    41.0     40.0     50.0     65.0   65.0         1.0       NaN           NaN      NaN  NaN
46                38                       Ninetales      Fire       NaN            505.0   73.0    76.0     75.0     81.0    100.0  100.0         1.0       NaN           NaN      NaN  NaN
47                39                      Jigglypuff    Normal     Fairy            270.0  115.0    45.0     20.0     45.0     25.0   20.0         1.0       NaN           NaN      NaN  NaN
48                40                      Wigglytuff    Normal     Fairy            435.0  140.0    70.0     45.0     85.0     50.0   45.0         1.0       NaN           NaN      NaN  NaN
49                41                           Zubat    Poison    Flying            245.0   40.0    45.0     35.0     30.0     40.0   55.0         1.0       NaN           NaN      NaN  NaN
50                42                          Golbat    Poison    Flying            455.0   75.0    80.0     70.0     65.0     75.0   90.0         1.0       NaN           NaN      NaN  NaN
51                43                          Oddish     Grass    Poison            320.0   45.0    50.0     55.0     75.0     65.0   30.0         1.0       NaN           NaN      NaN  NaN
52                44                           Gloom     Grass    Poison            395.0   60.0    65.0     70.0     85.0     75.0   40.0         1.0       NaN           NaN      NaN  NaN
53                45                       Vileplume     Grass    Poison            490.0   75.0    80.0     85.0    110.0     90.0   50.0         1.0       NaN           NaN      NaN  NaN
54                46                           Paras       Bug     Grass            285.0   35.0    70.0     55.0     45.0     55.0   25.0         1.0       NaN           NaN      NaN  NaN
55                47                        Parasect       Bug     Grass            405.0   60.0    95.0     80.0     60.0     80.0   30.0         1.0       NaN           NaN      NaN  NaN
56                48                         Venonat       Bug    Poison            305.0   60.0    55.0     50.0     40.0     55.0   45.0         1.0       NaN           NaN      NaN  NaN
57                49                        Venomoth       Bug    Poison            450.0   70.0    65.0     60.0     90.0     75.0   90.0         1.0       NaN           NaN      NaN  NaN
58                50                         Diglett    Ground       NaN            265.0   10.0    55.0     25.0     35.0     45.0   95.0         1.0       NaN           NaN      NaN  NaN
59                51                         Dugtrio    Ground       NaN            405.0   35.0    80.0     50.0     50.0     70.0  120.0         1.0       NaN           NaN      NaN  NaN
60                52                          Meowth    Normal       NaN            290.0   40.0    45.0     35.0     40.0     40.0   90.0         1.0       NaN           NaN      NaN  NaN
61                53                         Persian    Normal       NaN            440.0   65.0    70.0     60.0     65.0     65.0  115.0         1.0       NaN           NaN      NaN  NaN
62                54                         Psyduck     Water       NaN            320.0   50.0    52.0     48.0     65.0     50.0   55.0         1.0       NaN           NaN      NaN  NaN
63                55                         Golduck     Water       NaN            500.0   80.0    82.0     78.0     95.0     80.0   85.0         1.0       NaN           NaN      NaN  NaN
64                56                          Mankey  Fighting       NaN            305.0   40.0    80.0     35.0     35.0     45.0   70.0         1.0       NaN           NaN      NaN  NaN
65                57                        Primeape  Fighting       NaN            455.0   65.0   105.0     60.0     60.0     70.0   95.0         1.0       NaN           NaN      NaN  NaN
66                58                       Growlithe      Fire       NaN            350.0   55.0    70.0     45.0     70.0     50.0   60.0         1.0       NaN           NaN      NaN  NaN
67                59                        Arcanine      Fire       NaN            555.0   90.0   110.0     80.0    100.0     80.0   95.0         1.0       NaN           NaN      NaN  NaN
68                60                         Poliwag     Water       NaN            300.0   40.0    50.0     40.0     40.0     40.0   90.0         1.0       NaN           NaN      NaN  NaN
69                61                       Poliwhirl     Water       NaN            385.0   65.0    65.0     65.0     50.0     50.0   90.0         1.0       NaN           NaN      NaN  NaN
70                62                       Poliwrath     Water  Fighting            510.0   90.0    95.0     95.0     70.0     90.0   70.0         1.0       NaN           NaN      NaN  NaN
71                63                            Abra   Psychic       NaN            310.0   25.0    20.0     15.0    105.0     55.0   90.0         1.0       NaN           NaN      NaN  NaN
72                64                         Kadabra   Psychic       NaN            400.0   40.0    35.0     30.0    120.0     70.0  105.0         1.0       NaN           NaN      NaN  NaN
73                65                        Alakazam   Psychic       NaN            500.0   55.0    50.0     45.0    135.0     95.0  120.0         1.0       NaN           NaN      NaN  NaN
74                65                   Mega Alakazam   Psychic       NaN            590.0   55.0    50.0     65.0    175.0     95.0  150.0         1.0       NaN           NaN      NaN  NaN
75                66                          Machop  Fighting       NaN            305.0   70.0    80.0     50.0     35.0     35.0   35.0         1.0       NaN           NaN      NaN  NaN
76                67                         Machoke  Fighting       NaN            405.0   80.0   100.0     70.0     50.0     60.0   45.0         1.0       NaN           NaN      NaN  NaN
77                68                         Machamp  Fighting       NaN            505.0   90.0   130.0     80.0     65.0     85.0   55.0         1.0       NaN           NaN      NaN  NaN
78                69                      Bellsprout     Grass    Poison            300.0   50.0    75.0     35.0     70.0     30.0   40.0         1.0       NaN           NaN      NaN  NaN
79                70                      Weepinbell     Grass    Poison            390.0   65.0    90.0     50.0     85.0     45.0   55.0         1.0       NaN           NaN      NaN  NaN
80                71                      Victreebel     Grass    Poison            490.0   80.0   105.0     65.0    100.0     70.0   70.0         1.0       NaN           NaN      NaN  NaN
81                71                 Mega Victreebel       NaN       NaN              NaN    NaN     NaN      NaN      NaN      NaN    NaN         NaN       NaN           NaN      NaN  NaN
82                72                       Tentacool     Water    Poison            335.0   40.0    40.0     35.0     50.0    100.0   70.0         1.0       NaN           NaN      NaN  NaN
83                73                      Tentacruel     Water    Poison            515.0   80.0    70.0     65.0     80.0    120.0  100.0         1.0       NaN           NaN      NaN  NaN
84                74                         Geodude      Rock    Ground            300.0   40.0    80.0    100.0     30.0     30.0   20.0         1.0       NaN           NaN      NaN  NaN
85                75                        Graveler      Rock    Ground            390.0   55.0    95.0    115.0     45.0     45.0   35.0         1.0       NaN           NaN      NaN  NaN
86                76                           Golem      Rock    Ground            495.0   80.0   120.0    130.0     55.0     65.0   45.0         1.0       NaN           NaN      NaN  NaN
87                77                          Ponyta      Fire       NaN            410.0   50.0    85.0     55.0     65.0     65.0   90.0         1.0       NaN           NaN      NaN  NaN
88                78                        Rapidash      Fire       NaN            500.0   65.0   100.0     70.0     80.0     80.0  105.0         1.0       NaN           NaN      NaN  NaN
89                79                        Slowpoke     Water   Psychic            315.0   90.0    65.0     65.0     40.0     40.0   15.0         1.0       NaN           NaN      NaN  NaN
90                80                         Slowbro     Water   Psychic            490.0   95.0    75.0    110.0    100.0     80.0   30.0         1.0       NaN           NaN      NaN  NaN
91                80                    Mega Slowbro     Water   Psychic            590.0   95.0    75.0    180.0    130.0     80.0   30.0         1.0       NaN           NaN      NaN  NaN
92                81                       Magnemite  Electric     Steel            325.0   25.0    35.0     70.0     95.0     55.0   45.0         1.0       NaN           NaN      NaN  NaN
93                82                        Magneton  Electric     Steel            465.0   50.0    60.0     95.0    120.0     70.0   70.0         1.0       NaN           NaN      NaN  NaN
94                83                      Farfetch'd    Normal    Flying            352.0   52.0    65.0     55.0     58.0     62.0   60.0         1.0       NaN           NaN      NaN  NaN
95                84                           Doduo    Normal    Flying            310.0   35.0    85.0     45.0     35.0     35.0   75.0         1.0       NaN           NaN      NaN  NaN
96                85                          Dodrio    Normal    Flying            460.0   60.0   110.0     70.0     60.0     60.0  100.0         1.0       NaN           NaN      NaN  NaN
97                86                            Seel     Water       NaN            325.0   65.0    45.0     55.0     45.0     70.0   45.0         1.0       NaN           NaN      NaN  NaN
98                87                         Dewgong     Water       Ice            475.0   90.0    70.0     80.0     70.0     95.0   70.0         1.0       NaN           NaN      NaN  NaN
99                88                          Grimer    Poison       NaN            325.0   80.0    80.0     50.0     40.0     50.0   25.0         1.0       NaN           NaN      NaN  NaN
100               89                             Muk    Poison       NaN            500.0  105.0   105.0     75.0     65.0    100.0   50.0         1.0       NaN           NaN      NaN  NaN
101               90                        Shellder     Water       NaN            305.0   30.0    65.0    100.0     45.0     25.0   40.0         1.0       NaN           NaN      NaN  NaN
102               91                        Cloyster     Water       Ice            525.0   50.0    95.0    180.0     85.0     45.0   70.0         1.0       NaN           NaN      NaN  NaN
103               92                          Gastly     Ghost    Poison            310.0   30.0    35.0     30.0    100.0     35.0   80.0         1.0       NaN           NaN      NaN  NaN

In [85]:
# selection by column and updating a value in the dataframe, for example changing the type of Pidgey to Flying

df.loc[df["Name"] == "Pidgey", "Type 1"] = "Flying"
print(df.loc[df["Name"] == "Pidgey"])

# we can implement multiple conditions as well, for example if we want to get the pokemon whose type is fire and attack is greater than 50

print(df[(df["Type 1"] == "Fire") & (df["Attack"] > 50)].to_string())

    Pokedex Number    Name  Type 1  Type 2  Base Stat Total    HP  Attack  \
20              16  Pidgey  Flying  Flying            251.0  40.0    45.0

    Defense  Sp. Atk  Sp. Def  Speed  Generation Legendary Sub Legendary  \
20     40.0     35.0     35.0   56.0         1.0       NaN           NaN

   Mythical Mega
20      NaN  NaN
      Pokedex Number                        Name Type 1    Type 2  Base Stat Total     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation Legendary Sub Legendary Mythical Mega
4                  4                  Charmander   Fire       NaN            309.0   39.0    52.0     43.0     60.0     50.0   65.0         1.0       NaN           NaN      NaN  NaN
5                  5                  Charmeleon   Fire       NaN            405.0   58.0    64.0     58.0     80.0     65.0   80.0         1.0       NaN           NaN      NaN  NaN
6                  6                   Charizard   Fire    Flying            534.0   78.0    84.0     78.0    109.0     85.0  100.0         1.0       NaN           NaN      NaN  NaN
7                  6            Mega Charizard X   Fire    Dragon            634.0   78.0   130.0    111.0    130.0     85.0  100.0         1.0       NaN           NaN      NaN  NaN
8                  6            Mega Charizard Y   Fire    Flying            634.0   78.0   104.0     78.0    159.0    115.0  100.0         1.0       NaN           NaN      NaN  NaN
46                38                   Ninetales   Fire       NaN            505.0   73.0    76.0     75.0     81.0    100.0  100.0         1.0       NaN           NaN      NaN  NaN
66                58                   Growlithe   Fire       NaN            350.0   55.0    70.0     45.0     70.0     50.0   60.0         1.0       NaN           NaN      NaN  NaN
67                59                    Arcanine   Fire       NaN            555.0   90.0   110.0     80.0    100.0     80.0   95.0         1.0       NaN           NaN      NaN  NaN
87                77                      Ponyta   Fire       NaN            410.0   50.0    85.0     55.0     65.0     65.0   90.0         1.0       NaN           NaN      NaN  NaN
88                78                    Rapidash   Fire       NaN            500.0   65.0   100.0     70.0     80.0     80.0  105.0         1.0       NaN           NaN      NaN  NaN
140              126                      Magmar   Fire       NaN            495.0   65.0    95.0     57.0    100.0     85.0   93.0         1.0       NaN           NaN      NaN  NaN
152              136                     Flareon   Fire       NaN            525.0   65.0   130.0     60.0     95.0    110.0   65.0         1.0       NaN           NaN      NaN  NaN
163              146                     Moltres   Fire    Flying            580.0   90.0   100.0     90.0    125.0     85.0   90.0         1.0       NaN           NaN      NaN  NaN
176              155                   Cyndaquil   Fire       NaN            309.0   39.0    52.0     43.0     60.0     50.0   65.0         2.0       NaN           NaN      NaN  NaN
177              156                     Quilava   Fire       NaN            405.0   58.0    64.0     58.0     80.0     65.0   80.0         2.0       NaN           NaN      NaN  NaN
178              157                  Typhlosion   Fire       NaN            534.0   78.0    84.0     78.0    109.0     85.0  100.0         2.0       NaN           NaN      NaN  NaN
268              240                       Magby   Fire       NaN            365.0   45.0    75.0     37.0     70.0     55.0   83.0         2.0       NaN           NaN      NaN  NaN
272              244                       Entei   Fire       NaN            580.0  115.0   115.0     85.0     90.0     75.0  100.0         2.0       NaN           NaN      NaN  NaN
279              250                       Ho-oh   Fire    Flying            680.0  106.0   130.0     90.0    110.0    154.0   90.0         2.0       NaN           NaN      NaN  NaN
285              255                     Torchic   Fire       NaN            310.0   45.0    60.0     40.0     70.0     50.0   45.0         3.0       NaN           NaN      NaN  NaN
286              256                   Combusken   Fire  Fighting            405.0   60.0    85.0     60.0     85.0     60.0   55.0         3.0       NaN           NaN      NaN  NaN
287              257                    Blaziken   Fire  Fighting            530.0   80.0   120.0     70.0    110.0     70.0   80.0         3.0       NaN           NaN      NaN  NaN
288              257               Mega Blaziken   Fire  Fighting            630.0   80.0   160.0     80.0    130.0     80.0  100.0         3.0       NaN           NaN      NaN  NaN
361              322                       Numel   Fire    Ground            305.0   60.0    60.0     40.0     65.0     45.0   35.0         3.0       NaN           NaN      NaN  NaN
362              323                    Camerupt   Fire    Ground            460.0   70.0   100.0     70.0    105.0     75.0   40.0         3.0       NaN           NaN      NaN  NaN
363              323               Mega Camerupt   Fire    Ground            560.0   70.0   120.0    100.0    145.0    105.0   20.0         3.0       NaN           NaN      NaN  NaN
364              324                     Torkoal   Fire       NaN            470.0   70.0    85.0    140.0     85.0     70.0   20.0         3.0       NaN           NaN      NaN  NaN
446              390                    Chimchar   Fire       NaN            309.0   44.0    58.0     44.0     58.0     44.0   61.0         4.0       NaN           NaN      NaN  NaN
447              391                    Monferno   Fire  Fighting            405.0   64.0    78.0     52.0     78.0     52.0   81.0         4.0       NaN           NaN      NaN  NaN
448              392                   Infernape   Fire  Fighting            534.0   76.0   104.0     71.0    104.0     71.0  108.0         4.0       NaN           NaN      NaN  NaN
532              467                   Magmortar   Fire       NaN            540.0   75.0    95.0     67.0    125.0     95.0   83.0         4.0       NaN           NaN      NaN  NaN
557              485                     Heatran   Fire     Steel            600.0   91.0    90.0    106.0    130.0    106.0   77.0         4.0       NaN           NaN      NaN  NaN
574              498                       Tepig   Fire       NaN            308.0   65.0    63.0     45.0     45.0     45.0   45.0         5.0       NaN           NaN      NaN  NaN
575              499                     Pignite   Fire  Fighting            418.0   90.0    93.0     55.0     70.0     55.0   55.0         5.0       NaN           NaN      NaN  NaN
576              500                      Emboar   Fire  Fighting            528.0  110.0   123.0     65.0    100.0     65.0   65.0         5.0       NaN           NaN      NaN  NaN
590              513                     Pansear   Fire       NaN            316.0   50.0    53.0     48.0     53.0     48.0   64.0         5.0       NaN           NaN      NaN  NaN
591              514                    Simisear   Fire       NaN            498.0   75.0    98.0     63.0     98.0     63.0  101.0         5.0       NaN           NaN      NaN  NaN
634              554                    Darumaka   Fire       NaN            315.0   70.0    90.0     45.0     15.0     45.0   50.0         5.0       NaN           NaN      NaN  NaN
635              555  Darmanitan (Standard Mode)   Fire       NaN            480.0  105.0   140.0     55.0     30.0     55.0   95.0         5.0       NaN           NaN      NaN  NaN
716              631                     Heatmor   Fire       NaN            484.0   85.0    97.0     66.0    105.0     66.0   65.0         5.0       NaN           NaN      NaN  NaN
747              654                     Braixen   Fire       NaN            409.0   59.0    59.0     58.0     90.0     70.0   73.0         6.0       NaN           NaN      NaN  NaN
748              655                     Delphox   Fire   Psychic            534.0   75.0    69.0     72.0    114.0    100.0  104.0         6.0       NaN           NaN      NaN  NaN
757              662                 Fletchinder   Fire    Flying            382.0   62.0    73.0     55.0     56.0     52.0   84.0         6.0       NaN           NaN      NaN  NaN
758              663                  Talonflame   Fire    Flying            499.0   78.0    81.0     71.0     74.0     69.0  126.0         6.0       NaN           NaN      NaN  NaN
763              668                      Pyroar   Fire    Normal            507.0   86.0    68.0     72.0    109.0     66.0  106.0         6.0       NaN           NaN      NaN  NaN
835              721                   Volcanion   Fire     Water            600.0   80.0   110.0    120.0    130.0     90.0   70.0         6.0       NaN           NaN      NaN  NaN
839              725                      Litten   Fire       NaN            320.0   45.0    65.0     40.0     60.0     40.0   70.0         7.0       NaN           NaN      NaN  NaN
840              726                    Torracat   Fire       NaN            420.0   65.0    85.0     50.0     80.0     50.0   90.0         7.0       NaN           NaN      NaN  NaN
841              727                  Incineroar   Fire      Dark            530.0   95.0   115.0     90.0     80.0     90.0   60.0         7.0       NaN           NaN      NaN  NaN
856              741                    Oricorio   Fire    Flying            476.0   75.0    70.0     70.0     98.0     70.0   93.0         7.0       NaN           NaN      NaN  NaN
892              776                  Turtonator   Fire    Dragon            485.0   60.0    75.0    135.0     91.0     85.0   36.0         7.0       NaN           NaN      NaN  NaN
925              806                 Blacephalon   Fire     Ghost            570.0   53.0   127.0     53.0    151.0     79.0  107.0         7.0       NaN           NaN      NaN  NaN
934              814                      Raboot   Fire       NaN            420.0   65.0    86.0     60.0     55.0     60.0   94.0         8.0       NaN           NaN      NaN  NaN
935              815                   Cinderace   Fire       NaN            530.0   80.0   116.0     75.0     65.0     75.0  119.0         8.0       NaN           NaN      NaN  NaN
970              850                  Sizzlipede   Fire       Bug            305.0   50.0    65.0     45.0     50.0     50.0   45.0         8.0       NaN           NaN      NaN  NaN
971              851                 Centiskorch   Fire       Bug            525.0  100.0   115.0     65.0     90.0     90.0   65.0         8.0       NaN           NaN      NaN  NaN
1031             910                    Crocalor   Fire       NaN            411.0   81.0    55.0     78.0     90.0     58.0   49.0         9.0       NaN           NaN      NaN  NaN
1032             911                  Skeledirge   Fire     Ghost            530.0  104.0    75.0    100.0    110.0     75.0   66.0         9.0       NaN           NaN      NaN  NaN
1057             936                   Armarouge   Fire   Psychic            525.0   85.0    60.0    100.0    125.0     80.0   75.0         9.0       NaN           NaN      NaN  NaN
1058             937                   Ceruledge   Fire     Ghost            525.0   75.0   125.0     80.0     60.0    100.0   85.0         9.0       NaN           NaN      NaN  NaN
1120             994                   Iron Moth   Fire    Poison            570.0   80.0    70.0     60.0    140.0    110.0  110.0         9.0       NaN           NaN      NaN  NaN
1147            1020                Gouging Fire   Fire    Dragon            590.0  105.0   115.0    121.0     65.0     93.0   91.0         9.0       NaN           NaN      NaN  NaN

In [86]:
# we can set the lable of each row to be the name to make it easy for indexing and accessing the data, for that we will use set_index() function and pass the column name which we want to set as index

df.set_index("Name", inplace=True)  # Setting 'Name' column as index and modifying the original dataframe
print(df.loc["Pidgey"])  # Now we can access Pidgey directly using

Pokedex Number         16
Type 1             Flying
Type 2             Flying
Base Stat Total     251.0
HP                   40.0
Attack               45.0
Defense              40.0
Sp. Atk              35.0
Sp. Def              35.0
Speed                56.0
Generation            1.0
Legendary             NaN
Sub Legendary         NaN
Mythical              NaN
Mega                  NaN
Name: Pidgey, dtype: object

In [95]:
# we can also direclty do this while loadig the dataset

df_new = pd.read_csv("../Resources/Data/Pokemon.csv", index_col="Name")
print(df_new.loc["Pidgey"])

Pokedex Number         16
Type 1             Normal
Type 2             Flying
Base Stat Total     251.0
HP                   40.0
Attack               45.0
Defense              40.0
Sp. Atk              35.0
Sp. Def              35.0
Speed                56.0
Generation            1.0
Legendary             NaN
Sub Legendary         NaN
Mythical              NaN
Mega                  NaN
Name: Pidgey, dtype: object

## Dataframe Attributes

1. `shape` : This attribute returns the number of rows and columns in the DataFrame as a tuple (rows, columns).
2. `dtypes` : This attribute returns the data types of each column in the DataFrame as a series.
---
3. `info()` : This method provides a concise summary of the DataFrame, including the number of non-null values, data types, and memory usage.
4. `describe()` : This method generates descriptive statistics of the DataFrame, such as count, mean, standard deviation, minimum, and maximum values for each numeric column.
---
5. `head(n)` : This method returns the first n rows of the DataFrame. By default, it returns the first 5 rows.
6. `tail(n)` : This method returns the last n rows of the DataFrame. By default, it returns the last 5 rows.
7. `sample(n)` : This method returns a random sample of n rows from the DataFrame. By default, it returns 1 row.

In [6]:
df.shape  # (rows, columns) of the dataframe

(10000, 12)

In [7]:
df.dtypes # datatype of each column ( feature ) of the dataframe

Date                     str
Year                   int64
Locality                 str
Estimated Value      float64
Sale Price           float64
Property                 str
Residential              str
num_rooms              int64
num_bathrooms          int64
carpet_area          float64
property_tax_rate    float64
Face                     str
dtype: object

In [8]:
df.info() # type, range index, columns details, contained datatypes, memory usage

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               10000 non-null  str
 1   Year               10000 non-null  int64
 2   Locality           8747 non-null   str
 3   Estimated Value    8757 non-null   float64
 4   Sale Price         10000 non-null  float64
 5   Property           10000 non-null  str
 6   Residential        10000 non-null  str
 7   num_rooms          10000 non-null  int64
 8   num_bathrooms      10000 non-null  int64
 9   carpet_area        8771 non-null   float64
 10  property_tax_rate  10000 non-null  float64
 11  Face               10000 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 937.6 KB

In [9]:
df.describe()  # mean, standard deviation, minimum, maximum and others of the dataframe

,Year,Estimated Value,Sale Price,num_rooms,num_bathrooms,carpet_area,property_tax_rate
count,10000.000000,8.757000e+03,1.000000e+04,10000.000000,10000.000000,8771.000000,10000.000000
mean,2015.904900,4.377749e+05,6.129367e+05,3.335000,2.326400,1115.160871,1.148257
std,4.045725,7.799885e+05,1.102810e+06,0.886258,1.207977,308.026850,0.168458
min,2009.000000,9.800000e+02,2.000000e+03,3.000000,1.000000,900.000000,1.003979
25%,2012.000000,1.280300e+05,1.560000e+05,3.000000,1.000000,960.000000,1.023495
50%,2016.000000,2.300200e+05,3.250000e+05,3.000000,2.000000,1021.000000,1.025899
75%,2019.000000,4.253200e+05,6.150000e+05,3.000000,3.000000,1083.000000,1.348259
max,2022.000000,2.111991e+07,2.575000e+07,8.000000,8.000000,2989.000000,1.422308

In [10]:
df.head() # by default first 5 data, takes n = no of rows to show as param

df.head(2)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
0,2009-01-02,2009,Waterbury,111440.0,185000.0,Single Family,Detached House,3,3,996.0,1.025953,South
1,2009-01-02,2009,Bridgeport,124670.0,150000.0,Two Family,Duplex,4,3,1241.0,1.025953,South

In [11]:
df.tail() # by default last 5 data, takes n = no of rows to show as param

df.tail(2)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
9998,2022-09-30,2022,NaN,216420.0,415000.0,Single Family,Detached House,3,3,1014.0,1.003979,North
9999,2022-09-30,2022,Norwalk,154920.0,196000.0,Single Family,Detached House,3,1,932.0,1.003979,East

In [12]:
df.sample() # a random selected row of data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
4239,2015-09-27,2015,NaN,341740.0,1300000.0,?,Detached House,3,2,NaN,1.340225,South

In [13]:
# using head() and tail() together we can do indexing

df.head(56).tail(1)

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
55,2009-01-23,2009,Bridgeport,89670.0,266000.0,Two Family,Duplex,4,3,NaN,1.025953,West

In [14]:
df.iloc[56:60] # it works like slicing, in other words it is like sclicing thought the data

,Date,Year,Locality,Estimated Value,Sale Price,Property,Residential,num_rooms,num_bathrooms,carpet_area,property_tax_rate,Face
56,2009-01-24,2009,Waterbury,83930.0,240000.0,Three Family,Triplex,6,4,1899.0,1.025953,South
57,2009-01-24,2009,Bridgeport,114736.0,275000.0,Single Family,Detached House,3,2,1007.0,1.025953,East
58,2009-01-24,2009,Bridgeport,111720.0,265000.0,?,Detached House,3,3,947.0,1.025953,West
59,2009-01-25,2009,NaN,NaN,789000.0,Single Family,Detached House,3,1,923.0,1.025953,East

## Basic Statistics

In [ ]:
# aggregate functions are used to perform some operations on the data and return a single value

# mean aggregate function is used to get the mean of all the values in a column, for example if we want to get the mean of the attack column we can use the mean() function

print(df["Attack"].mean())  # it will return the mean of the attack column
print(
    df.mean(numeric_only=True)
)  # it will return the mean of all the numeric columns in the dataframe

# sum aggregate function is used to get the sum of all the values in a column, for example if we want to get the sum of the attack column we can use the sum() function

print(df["Attack"].sum())  # it will return the sum of the attack column
print(
    df.sum(numeric_only=True)
)  # it will return the sum of all the numeric columns in the dataframe

# min aggregate function is used to get the minimum value in a column, for example if we want to get the minimum value of the attack column we can use the min() function

print(df["Attack"].min())  # it will return the minimum value of the attack column
print(
    df.min(numeric_only=True)
)  # it will return the minimum value of all the numeric columns in the dataframe

# max aggregate function is used to get the maximum value in a column, for example if we want to get the maximum value of the attack column we can use the max() function

print(df["Attack"].max())  # it will return the maximum value of the attack column
print(
    df.max(numeric_only=True)
)  # it will return the maximum value of all the numeric columns in the dataframe

# count aggregate function is used to get the count of all the values in a column, for example if we want to get the count of the attack column we can use the count() function

print(df["Attack"].count())  # it will return the count of the attack column
print(
    df.count(numeric_only=True)
)  # it will return the count of all the numeric columns in the dataframe

80.22010869565217
Pokedex Number     506.361665
Base Stat Total    439.358696
HP                  70.655797
Attack              80.220109
Defense             74.507246
Sp. Atk             72.951993
Sp. Def             72.000906
Speed               68.994565
Generation           4.640399
dtype: float64
88563.0
Pokedex Number     583835.0
Base Stat Total    485052.0
HP                  78004.0
Attack              88563.0
Defense             82256.0
Sp. Atk             80539.0
Sp. Def             79489.0
Speed               76170.0
Generation           5123.0
dtype: float64
5.0
Pokedex Number       1.0
Base Stat Total    175.0
HP                   1.0
Attack               5.0
Defense              5.0
Sp. Atk             10.0
Sp. Def             20.0
Speed                5.0
Generation           1.0
dtype: float64
190.0
Pokedex Number     1025.0
Base Stat Total     780.0
HP                  255.0
Attack              190.0
Defense             230.0
Sp. Atk             194.0
Sp. Def             230.0
Speed               200.0
Generation            9.0
dtype: float64
1104
Pokedex Number     1153
Base Stat Total    1104
HP                 1104
Attack             1104
Defense            1104
Sp. Atk            1104
Sp. Def            1104
Speed              1104
Generation         1104
dtype: int64

In [ ]:
# grouping is used to group the data based on a column and perform some aggregate function on it, for example if we want to group the data based on the type of pokemon and get the mean of the attack column for each type we can use the groupby() function

grouped = df.groupby("Type 1")  # grouping the data based on the 'Type 1' column
print(grouped["Attack"].mean())  # getting the mean of the attack column for each type

Type 1
Bug          72.144444
Dark         89.270833
Dragon      106.911111
Electric     73.208955
Fairy        67.862069
Fighting    103.642857
Fire         84.600000
Flying       78.545455
Ghost        73.386364
Grass        75.453704
Ground       96.214286
Ice          75.218750
Normal       76.032787
Poison       75.309524
Psychic      71.042857
Rock         89.737705
Steel        92.536585
Water        74.685714
Name: Attack, dtype: float64

In [104]:
# data cleaning - the process of removing or correcting the data which is incorrect, incomplete, irrelevant or duplicated in the dataset

# drop() function is used to drop the rows or columns from the dataframe, for example if we want to drop the column 'Type 2' from the dataframe we can use the drop() function

df = df.drop(
    columns=["Legendary"], errors='ignore'
)  # dropping the 'Legendary' column from the dataframe - since it returns a new dataframe we need to assign it back to df to modify the original dataframe

print(df.to_string())

                                Pokedex Number    Type 1    Type 2  Base Stat Total     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation Sub Legendary Mythical Mega
Name
Bulbasaur                                    1     Grass    Poison            318.0   45.0    49.0     49.0     65.0     65.0   45.0         1.0            No       No   No
Ivysaur                                      2     Grass    Poison            405.0   60.0    62.0     63.0     80.0     80.0   60.0         1.0           NaN      NaN  NaN
Venusaur                                     3     Grass    Poison            525.0   80.0    82.0     83.0    100.0    100.0   80.0         1.0           NaN      NaN  NaN
Mega Venusaur                                3     Grass    Poison            625.0   80.0   100.0    123.0    122.0    120.0   80.0         1.0           NaN      NaN  NaN
Charmander                                   4      Fire       NaN            309.0   39.0    52.0     43.0     60.0     50.0   65.0         1.0           NaN      NaN  NaN
Charmeleon                                   5      Fire       NaN            405.0   58.0    64.0     58.0     80.0     65.0   80.0         1.0           NaN      NaN  NaN
Charizard                                    6      Fire    Flying            534.0   78.0    84.0     78.0    109.0     85.0  100.0         1.0           NaN      NaN  NaN
Mega Charizard X                             6      Fire    Dragon            634.0   78.0   130.0    111.0    130.0     85.0  100.0         1.0           NaN      NaN  NaN
Mega Charizard Y                             6      Fire    Flying            634.0   78.0   104.0     78.0    159.0    115.0  100.0         1.0           NaN      NaN  NaN
Squirtle                                     7     Water       NaN            314.0   44.0    48.0     65.0     50.0     64.0   43.0         1.0           NaN      NaN  NaN
Wartortle                                    8     Water       NaN            405.0   59.0    63.0     80.0     65.0     80.0   58.0         1.0           NaN      NaN  NaN
Blastoise                                    9     Water       NaN            530.0   79.0    83.0    100.0     85.0    105.0   78.0         1.0           NaN      NaN  NaN
Mega Blastoise                               9     Water       NaN            630.0   79.0   103.0    120.0    135.0    115.0   78.0         1.0           NaN      NaN  NaN
Caterpie                                    10       Bug       NaN            195.0   45.0    30.0     35.0     20.0     20.0   45.0         1.0           NaN      NaN  NaN
Metapod                                     11       Bug       NaN            205.0   50.0    20.0     55.0     25.0     25.0   30.0         1.0           NaN      NaN  NaN
Butterfree                                  12       Bug    Flying            395.0   60.0    45.0     50.0     90.0     80.0   70.0         1.0           NaN      NaN  NaN
Weedle                                      13       Bug    Poison            195.0   40.0    35.0     30.0     20.0     20.0   50.0         1.0           NaN      NaN  NaN
Kakuna                                      14       Bug    Poison            205.0   45.0    25.0     50.0     25.0     25.0   35.0         1.0           NaN      NaN  NaN
Beedrill                                    15       Bug    Poison            395.0   65.0    90.0     40.0     45.0     80.0   75.0         1.0           NaN      NaN  NaN
Mega Beedrill                               15       Bug    Poison            495.0   65.0   150.0     40.0     15.0     80.0  145.0         1.0           NaN      NaN  NaN
Pidgey                                      16    Flying    Flying            251.0   40.0    45.0     40.0     35.0     35.0   56.0         1.0           NaN      NaN  NaN
Pidgeotto                                   17    Normal    Flying            349.0   63.0    60.0     55.0     50.0     50.0   71.0         1.0           NaN      NaN  NaN
Pidgeot                                     18    Normal    Flying            479.0   83.0    80.0     75.0     70.0     70.0  101.0         1.0           NaN      NaN  NaN
Mega Pidgeot                                18    Normal    Flying            579.0   83.0    80.0     80.0    135.0     80.0  121.0         1.0           NaN      NaN  NaN
Rattata                                     19    Normal       NaN            253.0   30.0    56.0     35.0     25.0     35.0   72.0         1.0           NaN      NaN  NaN
Raticate                                    20    Normal       NaN            413.0   55.0    81.0     60.0     50.0     70.0   97.0         1.0           NaN      NaN  NaN
Spearow                                     21    Normal    Flying            262.0   40.0    60.0     30.0     31.0     31.0   70.0         1.0           NaN      NaN  NaN
Fearow                                      22    Normal    Flying            442.0   65.0    90.0     65.0     61.0     61.0  100.0         1.0           NaN      NaN  NaN
Ekans                                       23    Poison       NaN            288.0   35.0    60.0     44.0     40.0     54.0   55.0         1.0           NaN      NaN  NaN
Arbok                                       24    Poison       NaN            438.0   60.0    85.0     69.0     65.0     79.0   80.0         1.0           NaN      NaN  NaN
Pikachu                                     25  Electric       NaN            320.0   35.0    55.0     40.0     50.0     50.0   90.0         1.0           NaN      NaN  NaN
Raichu                                      26  Electric       NaN            485.0   60.0    90.0     55.0     90.0     80.0  110.0         1.0           NaN      NaN  NaN
Mega Raichu X                               26       NaN       NaN              NaN    NaN     NaN      NaN      NaN      NaN    NaN         NaN           NaN      NaN  NaN
Mega Raichu Y                               26       NaN       NaN              NaN    NaN     NaN      NaN      NaN      NaN    NaN         NaN           NaN      NaN  NaN
Sandshrew                                   27    Ground       NaN            300.0   50.0    75.0     85.0     20.0     30.0   40.0         1.0           NaN      NaN  NaN
Sandslash                                   28    Ground       NaN            450.0   75.0   100.0    110.0     45.0     55.0   65.0         1.0           NaN      NaN  NaN
Nidoran (Female)                            29    Poison       NaN            275.0   55.0    47.0     52.0     40.0     40.0   41.0         1.0           NaN      NaN  NaN
Nidorina                                    30    Poison       NaN            365.0   70.0    62.0     67.0     55.0     55.0   56.0         1.0           NaN      NaN  NaN
Nidoqueen                                   31    Poison    Ground            505.0   90.0    92.0     87.0     75.0     85.0   76.0         1.0           NaN      NaN  NaN
Nidoran (Male)                              32    Poison       NaN            273.0   46.0    57.0     40.0     40.0     40.0   50.0         1.0           NaN      NaN  NaN
Nidorino                                    33    Poison       NaN            365.0   61.0    72.0     57.0     55.0     55.0   65.0         1.0           NaN      NaN  NaN
Nidoking                                    34    Poison    Ground            505.0   81.0   102.0     77.0     85.0     75.0   85.0         1.0           NaN      NaN  NaN
Clefairy                                    35     Fairy       NaN            323.0   70.0    45.0     48.0     60.0     65.0   35.0         1.0           NaN      NaN  NaN
Clefable                                    36     Fairy       NaN            483.0   95.0    70.0     73.0     95.0     90.0   60.0         1.0           NaN      NaN  NaN
Mega Clefable                               36       NaN       NaN              NaN    NaN     NaN      NaN      NaN      NaN    NaN         NaN           NaN      NaN  NaN
Vulpix                                      37      Fire       NaN            299.0   38.0    41.0     40.0     50.0     65.0   65.0         1.0           NaN      NaN  NaN
Ninetales                                   38      Fire       NaN            505.0   73.0    76.0     75.0     81.0    100.0  100.0         1.0           NaN      NaN  NaN
Jigglypuff                                  39    Normal     Fairy            270.0  115.0    45.0     20.0     45.0     25.0   20.0         1.0           NaN      NaN  NaN
Wigglytuff                                  40    Normal     Fairy            435.0  140.0    70.0     45.0     85.0     50.0   45.0         1.0           NaN      NaN  NaN
Zubat                                       41    Poison    Flying            245.0   40.0    45.0     35.0     30.0     40.0   55.0         1.0           NaN      NaN  NaN
Golbat                                      42    Poison    Flying            455.0   75.0    80.0     70.0     65.0     75.0   90.0         1.0           NaN      NaN  NaN
Oddish                                      43     Grass    Poison            320.0   45.0    50.0     55.0     75.0     65.0   30.0         1.0           NaN      NaN  NaN
Gloom                                       44     Grass    Poison            395.0   60.0    65.0     70.0     85.0     75.0   40.0         1.0           NaN      NaN  NaN
Vileplume                                   45     Grass    Poison            490.0   75.0    80.0     85.0    110.0     90.0   50.0         1.0           NaN      NaN  NaN
Paras                                       46       Bug     Grass            285.0   35.0    70.0     55.0     45.0     55.0   25.0         1.0           NaN      NaN  NaN
Parasect                                    47       Bug     Grass            405.0   60.0    95.0     80.0     60.0     80.0   30.0         1.0           NaN      NaN  NaN
Venonat                                     48       Bug    Poison            305.0   60.0    55.0     50.0     40.0     55.0   45.0         1.0           NaN      NaN  NaN
Venomoth                                    49       Bug    Poison            450.0   70.0    65.0     60.0     90.0     75.0   90.0         1.0           NaN      NaN  NaN
Diglett                                     50    Ground       NaN            265.0   10.0    55.0     25.0     35.0     45.0   95.0         1.0           NaN      NaN  NaN
Dugtrio                                     51    Ground       NaN            405.0   35.0    80.0     50.0     50.0     70.0  120.0         1.0           NaN      NaN  NaN
Meowth                                      52    Normal       NaN            290.0   40.0    45.0     35.0     40.0     40.0   90.0         1.0           NaN      NaN  NaN
Persian                                     53    Normal       NaN            440.0   65.0    70.0     60.0     65.0     65.0  115.0         1.0           NaN      NaN  NaN
Psyduck                                     54     Water       NaN            320.0   50.0    52.0     48.0     65.0     50.0   55.0         1.0           NaN      NaN  NaN
Golduck                                     55     Water       NaN            500.0   80.0    82.0     78.0     95.0     80.0   85.0         1.0           NaN      NaN  NaN
Mankey                                      56  Fighting       NaN            305.0   40.0    80.0     35.0     35.0     45.0   70.0         1.0           NaN      NaN  NaN
Primeape                                    57  Fighting       NaN            455.0   65.0   105.0     60.0     60.0     70.0   95.0         1.0           NaN      NaN  NaN
Growlithe                                   58      Fire       NaN            350.0   55.0    70.0     45.0     70.0     50.0   60.0         1.0           NaN      NaN  NaN
Arcanine                                    59      Fire       NaN            555.0   90.0   110.0     80.0    100.0     80.0   95.0         1.0           NaN      NaN  NaN
Poliwag                                     60     Water       NaN            300.0   40.0    50.0     40.0     40.0     40.0   90.0         1.0           NaN      NaN  NaN
Poliwhirl                                   61     Water       NaN            385.0   65.0    65.0     65.0     50.0     50.0   90.0         1.0           NaN      NaN  NaN
Poliwrath                                   62     Water  Fighting            510.0   90.0    95.0     95.0     70.0     90.0   70.0         1.0           NaN      NaN  NaN
Abra                                        63   Psychic       NaN            310.0   25.0    20.0     15.0    105.0     55.0   90.0         1.0           NaN      NaN  NaN
Kadabra                                     64   Psychic       NaN            400.0   40.0    35.0     30.0    120.0     70.0  105.0         1.0           NaN      NaN  NaN
Alakazam                                    65   Psychic       NaN            500.0   55.0    50.0     45.0    135.0     95.0  120.0         1.0           NaN      NaN  NaN
Mega Alakazam                               65   Psychic       NaN            590.0   55.0    50.0     65.0    175.0     95.0  150.0         1.0           NaN      NaN  NaN
Machop                                      66  Fighting       NaN            305.0   70.0    80.0     50.0     35.0     35.0   35.0         1.0           NaN      NaN  NaN
Machoke                                     67  Fighting       NaN            405.0   80.0   100.0     70.0     50.0     60.0   45.0         1.0           NaN      NaN  NaN
Machamp                                     68  Fighting       NaN            505.0   90.0   130.0     80.0     65.0     85.0   55.0         1.0           NaN      NaN  NaN
Bellsprout                                  69     Grass    Poison            300.0   50.0    75.0     35.0     70.0     30.0   40.0         1.0           NaN      NaN  NaN
Weepinbell                                  70     Grass    Poison            390.0   65.0    90.0     50.0     85.0     45.0   55.0         1.0           NaN      NaN  NaN
Victreebel                                  71     Grass    Poison            490.0   80.0   105.0     65.0    100.0     70.0   70.0         1.0           NaN      NaN  NaN
Mega Victreebel                             71       NaN       NaN              NaN    NaN     NaN      NaN      NaN      NaN    NaN         NaN           NaN      NaN  NaN
Tentacool                                   72     Water    Poison            335.0   40.0    40.0     35.0     50.0    100.0   70.0         1.0           NaN      NaN  NaN
Tentacruel                                  73     Water    Poison            515.0   80.0    70.0     65.0     80.0    120.0  100.0         1.0           NaN      NaN  NaN
Geodude                                     74      Rock    Ground            300.0   40.0    80.0    100.0     30.0     30.0   20.0         1.0           NaN      NaN  NaN
Graveler                                    75      Rock    Ground            390.0   55.0    95.0    115.0     45.0     45.0   35.0         1.0           NaN      NaN  NaN
Golem                                       76      Rock    Ground            495.0   80.0   120.0    130.0     55.0     65.0   45.0         1.0           NaN      NaN  NaN
Ponyta                                      77      Fire       NaN            410.0   50.0    85.0     55.0     65.0     65.0   90.0         1.0           NaN      NaN  NaN
Rapidash                                    78      Fire       NaN            500.0   65.0   100.0     70.0     80.0     80.0  105.0         1.0           NaN      NaN  NaN
Slowpoke                                    79     Water   Psychic            315.0   90.0    65.0     65.0     40.0     40.0   15.0         1.0           NaN      NaN  NaN
Slowbro                                     80     Water   Psychic            490.0   95.0    75.0    110.0    100.0     80.0   30.0         1.0           NaN      NaN  NaN
Mega Slowbro                                80     Water   Psychic            590.0   95.0    75.0    180.0    130.0     80.0   30.0         1.0           NaN      NaN  NaN
Magnemite                                   81  Electric     Steel            325.0   25.0    35.0     70.0     95.0     55.0   45.0         1.0           NaN      NaN  NaN
Magneton                                    82  Electric     Steel            465.0   50.0    60.0     95.0    120.0     70.0   70.0         1.0           NaN      NaN  NaN
Farfetch'd                                  83    Normal    Flying            352.0   52.0    65.0     55.0     58.0     62.0   60.0         1.0           NaN      NaN  NaN
Doduo                                       84    Normal    Flying            310.0   35.0    85.0     45.0     35.0     35.0   75.0         1.0           NaN      NaN  NaN
Dodrio                                      85    Normal    Flying            460.0   60.0   110.0     70.0     60.0     60.0  100.0         1.0           NaN      NaN  NaN
Seel                                        86     Water       NaN            325.0   65.0    45.0     55.0     45.0     70.0   45.0         1.0           NaN      NaN  NaN
Dewgong                                     87     Water       Ice            475.0   90.0    70.0     80.0     70.0     95.0   70.0         1.0           NaN      NaN  NaN
Grimer                                      88    Poison       NaN            325.0   80.0    80.0     50.0     40.0     50.0   25.0         1.0           NaN      NaN  NaN
Muk                                         89    Poison       NaN            500.0  105.0   105.0     75.0     65.0    100.0   50.0         1.0           NaN      NaN  NaN
Shellder                                    90     Water       NaN            305.0   30.0    65.0    100.0     45.0     25.0   40.0         1.0           NaN      NaN  NaN
Cloyster                                    91     Water       Ice            525.0   50.0    95.0    180.0     85.0     45.0   70.0         1.0           NaN      NaN  NaN
Gastly                                      92     Ghost    Poison            310.0   30.0    35.0     30.0    100.0     35.0   80.0         1.0           NaN      NaN  NaN
Haunter                                     93     Ghost    Poison            405.0   45.0    50.0     45.0    115.0     55.0   95.0         1.0           NaN      NaN  NaN
Gengar                                      94     Ghost    Poison            500.0   60.0    65.0     60.0    130.0     75.0  110.0         1.0           NaN      NaN  NaN
Mega Gengar                                 94     Ghost    Poison            600.0   60.0    65.0     80.0    170.0     95.0  130.0         1.0           NaN      NaN  NaN
Onix                                        95      Rock    Ground            385.0   35.0    45.0    160.0     30.0     45.0   70.0         1.0           NaN      NaN  NaN
Drowzee                                     96   Psychic       NaN            328.0   60.0    48.0     45.0     43.0     90.0   42.0         1.0           NaN      NaN  NaN
Hypno                                       97   Psychic       NaN            483.0   85.0    73.0     70.0     73.0    115.0   67.0         1.0           NaN      NaN  NaN
Krabby                                      98     Water       NaN            325.0   30.0   105.0     90.0     25.0     25.0   50.0         1.0           NaN      NaN  NaN
Kingler                                     99     Water       NaN            475.0   55.0   130.0    115.0     50.0     50.0   75.0         1.0           NaN      NaN  NaN
Voltorb                                    100  Electric       NaN            330.0   40.0    30.0     50.0     55.0     55.0  100.0         1.0           NaN      NaN  NaN
Electrode                                  101  Electric       NaN            480.0   60.0    50.0     70.0     80.0     80.0  140.0         1.0           NaN      NaN  NaN

In [112]:
# handing missing data

# check for missing values in the dataframe and if there are any missing values then we can either drop the rows or columns which have missing values or we can fill the missing values with some value, for example if we want to fill the missing values with 0 we can use the fillna() function

df = df.dropna(
    subset=["Type 2"]
)  # dropping the rows which have missing values in the 'Type 2' column

# we will use fillna() function to fill the missing values, NaN with 0 or any other value
df = df.fillna(value=0)  # this will fill all the NaN values in the dataframe with 0

# wse can also pass in dictionary for doing specific column filling
df = df.fillna(
    {"Type 2": "No Type"}
)  # this will fill the NaN values in the 'Type 2' column with 'No Type'

# fixing in-consistent values - for example if we want to replace the value 'Fire' with 'Flame' in the 'Type 1' column we can use the replace() function

df["Type 1"] = df["Type 1"].replace(
    "Fire", "Flame"
)  # replacing 'Fire' with 'Flame' in the 'Type 1' column

# Standardizing the data - for example if we want to standardize the attack column we can use the following formula

df["Attack"] = (df["Attack"] - df["Attack"].mean()) / df["Attack"].std()

# or let's say we want all the Type 1 to be in uppercase we can use the str.upper() function

df["Type 1"] = df[
    "Type 1"
].str.upper()  # converting all the values in the 'Type 1' column to uppercase

# fixing the data types - for example if we want to convert the attack column to integer we can use the astype() function

df["Attack"] = df["Attack"].astype(int)  # converting the 'Attack' column to integer

# removing duplicates - for example if we want to remove the duplicate rows from the dataframe we can use the drop_duplicates() function

df = df.drop_duplicates()  # removing duplicate rows from the dataframe

print(df.to_string())

                            Pokedex Number    Type 1    Type 2  Base Stat Total     HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation Sub Legendary Mythical Mega
Name
Bulbasaur                                1     GRASS    Poison            318.0   45.0      -1     49.0     65.0     65.0   45.0         1.0            No       No   No
Ivysaur                                  2     GRASS    Poison            405.0   60.0       0     63.0     80.0     80.0   60.0         1.0             0        0    0
Venusaur                                 3     GRASS    Poison            525.0   80.0       0     83.0    100.0    100.0   80.0         1.0             0        0    0
Mega Venusaur                            3     GRASS    Poison            625.0   80.0       0    123.0    122.0    120.0   80.0         1.0             0        0    0
Charizard                                6     FLAME    Flying            534.0   78.0       0     78.0    109.0     85.0  100.0         1.0             0        0    0
Mega Charizard X                         6     FLAME    Dragon            634.0   78.0       1    111.0    130.0     85.0  100.0         1.0             0        0    0
Mega Charizard Y                         6     FLAME    Flying            634.0   78.0       0     78.0    159.0    115.0  100.0         1.0             0        0    0
Butterfree                              12       BUG    Flying            395.0   60.0      -1     50.0     90.0     80.0   70.0         1.0             0        0    0
Weedle                                  13       BUG    Poison            195.0   40.0      -1     30.0     20.0     20.0   50.0         1.0             0        0    0
Kakuna                                  14       BUG    Poison            205.0   45.0      -1     50.0     25.0     25.0   35.0         1.0             0        0    0
Beedrill                                15       BUG    Poison            395.0   65.0       0     40.0     45.0     80.0   75.0         1.0             0        0    0
Mega Beedrill                           15       BUG    Poison            495.0   65.0       1     40.0     15.0     80.0  145.0         1.0             0        0    0
Pidgey                                  16    FLYING    Flying            251.0   40.0      -1     40.0     35.0     35.0   56.0         1.0             0        0    0
Pidgeotto                               17    NORMAL    Flying            349.0   63.0       0     55.0     50.0     50.0   71.0         1.0             0        0    0
Pidgeot                                 18    NORMAL    Flying            479.0   83.0       0     75.0     70.0     70.0  101.0         1.0             0        0    0
Mega Pidgeot                            18    NORMAL    Flying            579.0   83.0       0     80.0    135.0     80.0  121.0         1.0             0        0    0
Spearow                                 21    NORMAL    Flying            262.0   40.0       0     30.0     31.0     31.0   70.0         1.0             0        0    0
Fearow                                  22    NORMAL    Flying            442.0   65.0       0     65.0     61.0     61.0  100.0         1.0             0        0    0
Nidoqueen                               31    POISON    Ground            505.0   90.0       0     87.0     75.0     85.0   76.0         1.0             0        0    0
Nidoking                                34    POISON    Ground            505.0   81.0       0     77.0     85.0     75.0   85.0         1.0             0        0    0
Jigglypuff                              39    NORMAL     Fairy            270.0  115.0      -1     20.0     45.0     25.0   20.0         1.0             0        0    0
Wigglytuff                              40    NORMAL     Fairy            435.0  140.0       0     45.0     85.0     50.0   45.0         1.0             0        0    0
Zubat                                   41    POISON    Flying            245.0   40.0      -1     35.0     30.0     40.0   55.0         1.0             0        0    0
Golbat                                  42    POISON    Flying            455.0   75.0       0     70.0     65.0     75.0   90.0         1.0             0        0    0
Oddish                                  43     GRASS    Poison            320.0   45.0      -1     55.0     75.0     65.0   30.0         1.0             0        0    0
Gloom                                   44     GRASS    Poison            395.0   60.0       0     70.0     85.0     75.0   40.0         1.0             0        0    0
Vileplume                               45     GRASS    Poison            490.0   75.0       0     85.0    110.0     90.0   50.0         1.0             0        0    0
Paras                                   46       BUG     Grass            285.0   35.0       0     55.0     45.0     55.0   25.0         1.0             0        0    0
Parasect                                47       BUG     Grass            405.0   60.0       0     80.0     60.0     80.0   30.0         1.0             0        0    0
Venonat                                 48       BUG    Poison            305.0   60.0       0     50.0     40.0     55.0   45.0         1.0             0        0    0
Venomoth                                49       BUG    Poison            450.0   70.0       0     60.0     90.0     75.0   90.0         1.0             0        0    0
Poliwrath                               62     WATER  Fighting            510.0   90.0       0     95.0     70.0     90.0   70.0         1.0             0        0    0
Bellsprout                              69     GRASS    Poison            300.0   50.0       0     35.0     70.0     30.0   40.0         1.0             0        0    0
Weepinbell                              70     GRASS    Poison            390.0   65.0       0     50.0     85.0     45.0   55.0         1.0             0        0    0
Victreebel                              71     GRASS    Poison            490.0   80.0       0     65.0    100.0     70.0   70.0         1.0             0        0    0
Tentacool                               72     WATER    Poison            335.0   40.0      -1     35.0     50.0    100.0   70.0         1.0             0        0    0
Tentacruel                              73     WATER    Poison            515.0   80.0       0     65.0     80.0    120.0  100.0         1.0             0        0    0
Geodude                                 74      ROCK    Ground            300.0   40.0       0    100.0     30.0     30.0   20.0         1.0             0        0    0
Graveler                                75      ROCK    Ground            390.0   55.0       0    115.0     45.0     45.0   35.0         1.0             0        0    0
Golem                                   76      ROCK    Ground            495.0   80.0       1    130.0     55.0     65.0   45.0         1.0             0        0    0
Slowpoke                                79     WATER   Psychic            315.0   90.0       0     65.0     40.0     40.0   15.0         1.0             0        0    0
Slowbro                                 80     WATER   Psychic            490.0   95.0       0    110.0    100.0     80.0   30.0         1.0             0        0    0
Mega Slowbro                            80     WATER   Psychic            590.0   95.0       0    180.0    130.0     80.0   30.0         1.0             0        0    0
Magnemite                               81  ELECTRIC     Steel            325.0   25.0      -1     70.0     95.0     55.0   45.0         1.0             0        0    0
Magneton                                82  ELECTRIC     Steel            465.0   50.0       0     95.0    120.0     70.0   70.0         1.0             0        0    0
Farfetch'd                              83    NORMAL    Flying            352.0   52.0       0     55.0     58.0     62.0   60.0         1.0             0        0    0
Doduo                                   84    NORMAL    Flying            310.0   35.0       0     45.0     35.0     35.0   75.0         1.0             0        0    0
Dodrio                                  85    NORMAL    Flying            460.0   60.0       0     70.0     60.0     60.0  100.0         1.0             0        0    0
Dewgong                                 87     WATER       Ice            475.0   90.0       0     80.0     70.0     95.0   70.0         1.0             0        0    0
Cloyster                                91     WATER       Ice            525.0   50.0       0    180.0     85.0     45.0   70.0         1.0             0        0    0
Gastly                                  92     GHOST    Poison            310.0   30.0      -1     30.0    100.0     35.0   80.0         1.0             0        0    0
Haunter                                 93     GHOST    Poison            405.0   45.0      -1     45.0    115.0     55.0   95.0         1.0             0        0    0
Gengar                                  94     GHOST    Poison            500.0   60.0       0     60.0    130.0     75.0  110.0         1.0             0        0    0
Mega Gengar                             94     GHOST    Poison            600.0   60.0       0     80.0    170.0     95.0  130.0         1.0             0        0    0
Onix                                    95      ROCK    Ground            385.0   35.0      -1    160.0     30.0     45.0   70.0         1.0             0        0    0
Exeggcute                              102     GRASS   Psychic            325.0   60.0      -1     80.0     60.0     45.0   40.0         1.0             0        0    0
Exeggutor                              103     GRASS   Psychic            520.0   95.0       0     85.0    125.0     65.0   55.0         1.0             0        0    0
Rhyhorn                                111    GROUND      Rock            345.0   80.0       0     95.0     30.0     30.0   25.0         1.0             0        0    0
Rhydon                                 112    GROUND      Rock            485.0  105.0       1    120.0     45.0     45.0   40.0         1.0             0        0    0
Starmie                                121     WATER   Psychic            520.0   60.0       0     85.0    100.0     85.0  115.0         1.0             0        0    0
Mr. Mime                               122   PSYCHIC     Fairy            460.0   40.0      -1     65.0    100.0    120.0   90.0         1.0             0        0    0
Scyther                                123       BUG    Flying            500.0   70.0       0     80.0     55.0     80.0  105.0         1.0             0        0    0
Jynx                                   124       ICE   Psychic            455.0   65.0      -1     35.0    115.0     95.0   95.0         1.0             0        0    0
Mega Pinsir                            127       BUG    Flying            600.0   65.0       2    120.0     65.0     90.0  105.0         1.0             0        0    0
Gyarados                               130     WATER    Flying            540.0   95.0       1     79.0     60.0    100.0   81.0         1.0             0        0    0
Mega Gyarados                          130     WATER      Dark            640.0   95.0       2    109.0     70.0    130.0   81.0         1.0             0        0    0
Lapras                                 131     WATER       Ice            535.0  130.0       0     80.0     85.0     95.0   60.0         1.0             0        0    0
Omanyte                                138      ROCK     Water            355.0   35.0      -1    100.0     90.0     55.0   35.0         1.0             0        0    0
Omastar                                139      ROCK     Water            495.0   70.0       0    125.0    115.0     70.0   55.0         1.0             0        0    0
Kabuto                                 140      ROCK     Water            355.0   30.0       0     90.0     55.0     45.0   55.0         1.0             0        0    0
Kabutops                               141      ROCK     Water            495.0   60.0       0    105.0     65.0     70.0   80.0         1.0             0        0    0
Aerodactyl                             142      ROCK    Flying            515.0   80.0       0     65.0     60.0     75.0  130.0         1.0             0        0    0
Mega Aerodactyl                        142      ROCK    Flying            615.0   80.0       1     85.0     70.0     95.0  150.0         1.0             0        0    0
Articuno                               144       ICE    Flying            580.0   90.0       0    100.0     95.0    125.0   85.0         1.0             0        0    0
Zapdos                                 145  ELECTRIC    Flying            580.0   90.0       0     85.0    125.0     90.0  100.0         1.0             0        0    0
Moltres                                146     FLAME    Flying            580.0   90.0       0     90.0    125.0     85.0   90.0         1.0             0        0    0
Dragonite                              149    DRAGON    Flying            600.0   91.0       1     95.0    100.0    100.0   80.0         1.0             0        0    0
Mega Mewtwo X                          150   PSYCHIC  Fighting            780.0  106.0       4    100.0    154.0    100.0  130.0         1.0             0        0    0
Hoothoot                               163    NORMAL    Flying            262.0   60.0      -1     30.0     36.0     56.0   50.0         2.0             0        0    0
Noctowl                                164    NORMAL    Flying            442.0  100.0      -1     50.0     76.0     96.0   70.0         2.0             0        0    0
Ledyba                                 165       BUG    Flying            265.0   40.0      -1     30.0     40.0     80.0   55.0         2.0             0        0    0
Ledian                                 166       BUG    Flying            390.0   55.0      -1     50.0     55.0    110.0   85.0         2.0             0        0    0
Spinarak                               167       BUG    Poison            250.0   40.0       0     40.0     40.0     40.0   30.0         2.0             0        0    0
Ariados                                168       BUG    Poison            390.0   70.0       0     70.0     60.0     60.0   40.0         2.0             0        0    0
Crobat                                 169    POISON    Flying            535.0   85.0       0     80.0     70.0     80.0  130.0         2.0             0        0    0
Chinchou                               170     WATER  Electric            330.0   75.0      -1     38.0     56.0     56.0   67.0         2.0             0        0    0
Lanturn                                171     WATER  Electric            460.0  125.0       0     58.0     76.0     76.0   67.0         2.0             0        0    0
Igglybuff                              174    NORMAL     Fairy            210.0   90.0      -1     15.0     40.0     20.0   15.0         2.0             0        0    0
Togetic                                176     FAIRY    Flying            405.0   55.0      -1     85.0     80.0    105.0   40.0         2.0             0        0    0
Natu                                   177   PSYCHIC    Flying            320.0   40.0      -1     45.0     70.0     45.0   70.0         2.0             0        0    0
Xatu                                   178   PSYCHIC    Flying            470.0   65.0       0     70.0     95.0     70.0   95.0         2.0             0        0    0
Mega Ampharos                          181  ELECTRIC    Dragon            610.0   90.0       0    105.0    165.0    110.0   45.0         2.0             0        0    0
Marill                                 183     WATER     Fairy            250.0   70.0      -1     50.0     20.0     50.0   40.0         2.0             0        0    0
Azumarill                              184     WATER     Fairy            420.0  100.0      -1     80.0     60.0     80.0   50.0         2.0             0        0    0
Hoppip                                 187     GRASS    Flying            250.0   35.0      -1     40.0     35.0     55.0   50.0         2.0             0        0    0
Skiploom                               188     GRASS    Flying            340.0   55.0      -1     50.0     45.0     65.0   80.0         2.0             0        0    0
Jumpluff                               189     GRASS    Flying            460.0   75.0       0     70.0     55.0     95.0  110.0         2.0             0        0    0
Yanma                                  193       BUG    Flying            390.0   65.0       0     45.0     75.0     45.0   95.0         2.0             0        0    0
Wooper                                 194     WATER    Ground            210.0   55.0      -1     45.0     25.0     25.0   15.0         2.0             0        0    0
Quagsire                               195     WATER    Ground            430.0   95.0       0     85.0     65.0     65.0   35.0         2.0             0        0    0
Murkrow                                198      DARK    Flying            405.0   60.0       0     42.0     85.0     42.0   91.0         2.0             0        0    0
Slowking                               199     WATER   Psychic            490.0   95.0       0     80.0    100.0    110.0   30.0         2.0             0        0    0
Girafarig                              203    NORMAL   Psychic            455.0   70.0       0     65.0     90.0     65.0   85.0         2.0             0        0    0
Forretress                             205       BUG     Steel            465.0   75.0       0    140.0     60.0     60.0   40.0         2.0             0        0    0
Gligar                                 207    GROUND    Flying            430.0   65.0       0    105.0     35.0     65.0   85.0         2.0             0        0    0
Steelix                                208     STEEL    Ground            510.0   75.0       0    200.0     55.0     65.0   30.0         2.0             0        0    0
Mega Steelix                           208     STEEL    Ground            610.0   75.0       1    230.0     55.0     95.0   30.0         2.0             0        0    0
Qwilfish                               211     WATER    Poison            430.0   65.0       0     75.0     55.0     55.0   85.0         2.0             0        0    0
Scizor                                 212       BUG     Steel            500.0   70.0       1    100.0     55.0     80.0   65.0         2.0             0        0    0
Mega Scizor                            212       BUG     Steel            600.0   70.0       1    140.0     65.0    100.0   75.0         2.0             0        0    0
Shuckle                                213       BUG      Rock            505.0   20.0      -3    230.0     10.0    230.0    5.0         2.0             0        0    0
Heracross                              214       BUG  Fighting            500.0   80.0       1     75.0     40.0     95.0   85.0         2.0             0        0    0
Mega Heracross                         214       BUG  Fighting            600.0   80.0       4    115.0     40.0    105.0   75.0         2.0             0        0    0
Sneasel                                215      DARK       Ice            430.0   55.0       0     55.0     35.0     75.0  115.0         2.0             0        0    0
Magcargo                               219     FLAME      Rock            410.0   50.0      -1    120.0     80.0     80.0   30.0         2.0             0        0    0
Swinub                                 220       ICE    Ground            250.0   50.0      -1     40.0     30.0     30.0   50.0         2.0             0        0    0
Piloswine                              221       ICE    Ground            450.0  100.0       0     80.0     60.0     60.0   50.0         2.0             0        0    0